New version

diff --git a/bin/epm b/bin/epm
--- a/bin/epm
+++ b/bin/epm
@@ -1,5 +1,18 @@
 #!/usr/bin/env bash
 
+# Add semantics to avoid packing without all the dependencies installed (remove work around in packages)
+# Add the tenant configuration to the packages
+# Correct problem with command_fail
+# Add best practices set command to epm
+# Add dynamic dependencies
+# Support for package configuration
+# Push only if updated
+# Add win support
+# Allow the listing of uninstalled packages 
+# Correct function naming of application install lib
+# Add support for listing via webdav
+# Adicionar biblioteca epm e resolver problema com jdev no wait for process
+
 VERSION_NUMBER="0.0.1"
 VERSION_DATE="04/07/2015"
 PROGRAM_FILE="$(basename $0)"
@@ -164,6 +177,11 @@ empty() {
     test -z "$1"
 }
 
+trim() {
+    log_trace "Trimming leading and trailing spaces from \"$1\""
+    echo -e "$1" | sed -e "s/^[[:space:]]*//" -e "s/[[:space:]]*$//"
+}
+
 replace() {
     log_trace "Replacing \"$2\" with \"$3\" in \"$1\""
     sed -r "s/$2/$3/g" <<< $1 
@@ -172,6 +190,19 @@ replace() {
 reverse() {
     log_trace "Reversing text \"$1\""
     sed -n '1!G;h;$p' <<< "$1"
+}
+
+csv_contains() {
+    log_trace "Checking if csv list \"$1\" has the \"$2\" element"
+    IFS=',' read -ra VALUES <<< "$1"
+    for VALUE in "${VALUES[@]}"; do
+        local TVALUE="$(trim "$VALUE")"
+        if [[ "$TVALUE" == "$2" ]]; then
+            return 0
+        fi
+    done
+
+    return 1
 }
 
 file_list() {
@@ -447,7 +478,7 @@ command_ok() {
 }
 
 command_fail() {
-    command_end "FAIL" "$1"
+    command_end "FAIL" "${1:-}"
     exit 1
 }
 
@@ -493,7 +524,7 @@ command_usage() {
 check() {
     log_trace "Checking base conditions"
     if ! file_exists "$EPM_ENV_FILE_PATH"; then
-        printf "fatal: Not a %s folder\n" "$PROGRAM_NAME"
+        printf "fatal: %s is not not a %s folder\n" "$EPM_ENV_FILE_PATH" "$PROGRAM_NAME"
         exit 1
     fi
 }
@@ -775,50 +806,118 @@ data_config_get_prop() {
     data_config_get "$1" | prop_get "$1:$2"
 }
 
+data_config_set_prop() {
+    awk -i inplace -F":" -v pkg="$1" -v prop="$2" -v val="$3" '
+        match($1, prop) { 
+            if ( cpkg == pkg ) {
+                $2=" "val
+            }
+        }
+        match($1, "^[a-zA-Z]{1}[a-zA-Z0-9_]*$") { cpkg=$1 }
+        { print $1":"$2}
+    ' "$EPM_DAT_FILE_PATH"
+}
+
+data_config_add_prop() {
+    awk -i inplace -F":" -v pkg="$1" -v prop="$2" -v val="$3" '
+        function ltrim(s) { sub(/^[ \t\r\n]+/, "", s); return s }
+        function rtrim(s) { sub(/[ \t\r\n]+$/, "", s); return s }
+        function trim(s) { return rtrim(ltrim(s)); }
+        match($1, prop) { 
+            if ( cpkg == pkg ) {
+                cval=trim($2);
+                if (length(cval)==0) {
+                    $2=" "val
+                } else {
+                    $2=" "cval","val 
+                }
+            }
+        }
+        match($1, "^[a-zA-Z]{1}[a-zA-Z0-9_]*$") { cpkg=$1 }
+        { print $1":"$2}
+    ' "$EPM_DAT_FILE_PATH"
+}
+
 data_config_get_type() {
     data_config_get_prop "$1" "$PKG_TYPE_KEY" 
+}
+
+data_config_is_single() {
+    local PKG_TYPE="$(data_config_get_type "$1")" 
+    [ "$PKG_TYPE" == "$PKG_TYPE_SINGLE" ]
+}
+
+data_config_is_bundle() {
+    local PKG_TYPE="$(data_config_get_type "$1")" 
+    [ "$PKG_TYPE" == "$PKG_TYPE_BUNDLE" ]
+}
+
+data_config_set_type() {
+    data_config_set_prop "$1" "$PKG_TYPE_KEY" "$2" 
 }
 
 data_config_get_env() {
     data_config_get_prop "$1" "$PKG_ENV_KEY" 
 }
 
+data_config_set_env() {
+    data_config_set_prop "$1" "$PKG_ENV_KEY" "$2" 
+}
+
 data_config_get_parent() {
     data_config_get_prop "$1" "$PKG_PARENT_KEY" 
+}
+
+data_config_set_parent() {
+    data_config_set_prop "$1" "$PKG_PARENT_KEY" "$2" 
 }
 
 data_config_get_dependencies() {
     data_config_get_prop "$1" "$PKG_DEPENDENCIES_KEY" 
 }
 
+data_config_add_dependencies() {
+    data_config_add_prop "$1" "$PKG_DEPENDENCIES_KEY" "$2" 
+}
+
+data_config_set_dependencies() {
+    data_config_set_prop "$1" "$PKG_DEPENDENCIES_KEY" "$2" 
+}
+
 data_config_get_description() {
     data_config_get_prop "$1" "$PKG_DESCRIPTION_KEY" 
 }
 
+data_config_set_description() {
+    data_config_set_prop "$1" "$PKG_DESCRIPTION_KEY" "$2" 
+}
+
 data_get_dependents() {
     MODE="$2"
-    MODE=${MODE:-$PKG_DEPENDENTS_MODE_ALL}
+    MODE="${MODE:-$PKG_DEPENDENTS_MODE_ALL}"
 
     log_trace "Getting all package dependents from \"$1\" in \"$MODE\" mode"
 
     while read -r PKG; do
         if [ "$MODE" == "$PKG_DEPENDENTS_MODE_PARENT" ]; then
-            PARENT="$(data_config_get_parent "$PKG")"
+            local PARENT="$(data_config_get_parent "$PKG")"
+            local TPARENT="$(trim "$PARENT")"
 
-            if [[ $PARENT == *"$1"* ]]; then
+            if [[ "$TPARENT" == "$1" ]]; then
                 printf "%s\n" "$PKG"
             fi        
         elif [ "$MODE" == "$PKG_DEPENDENTS_MODE_DEPENDENCIES" ]; then
-            DEPENDENCIES="$(data_config_get_dependencies "$PKG")"
+            local DEPENDENCIES="$(data_config_get_dependencies "$PKG")"
 
-            if [[ $DEPENDENCIES == *"$1"* ]]; then
+            if csv_contains "$DEPENDENCIES" "$1"; then
                 printf "%s\n" "$PKG"
             fi        
         elif [ "$MODE" == "$PKG_DEPENDENTS_MODE_ALL" ]; then
-            PARENT="$(data_config_get_parent "$PKG")"
-            DEPENDENCIES="$(data_config_get_dependencies "$PKG")"
+            local PARENT="$(data_config_get_parent "$PKG")"
+            local TPARENT="$(trim "$PARENT")"
+            local DEPENDENCIES="$(data_config_get_dependencies "$PKG")"
 
-            if [[ $PARENT == *"$1"* || $DEPENDENCIES == *"$1"* ]]; then
+            if [[ "$TPARENT" == "$1" ]] || csv_contains "$DEPENDENCIES" "$1"; then
                 printf "%s\n" "$PKG"
             fi        
         fi
@@ -1118,7 +1217,9 @@ lib_list_check() {
 }
 
 lib_list_exec() {
-    file_list "$EPM_LIB_PATH"
+    while read -r LIB_FILE_NAME; do
+        echo "${LIB_FILE_NAME%.*}"
+    done <<< "$(file_list "$EPM_LIB_PATH")"
 }
 
 lib_list() {
@@ -1231,7 +1332,7 @@ init_lib() {
     printf "\texec 1>&3 2>&4\n" >> "$EPM_LIB_FILE_PATH" 
     printf "}\n\n" >> "$EPM_LIB_FILE_PATH"
     printf "require() {\n" >> "$EPM_LIB_FILE_PATH"
-    printf "\t%s require \"%s\"\n" '$PROGRAM_PATH' '$1' >> "$EPM_LIB_FILE_PATH" 
+    printf "\t%s require \"%s\" \"%s\"\n" '$PROGRAM_PATH' '$1' '$2' >> "$EPM_LIB_FILE_PATH" 
     printf "}\n\n" >> "$EPM_LIB_FILE_PATH"
     printf "install() {\n" >> "$EPM_LIB_FILE_PATH"
     printf "\t%s install \"%s\"\n" '$PROGRAM_PATH' '$1' >> "$EPM_LIB_FILE_PATH" 
@@ -1456,44 +1557,22 @@ pull() {
 
 uninstall_exec() {
     UNINSTALL_PACKAGE="$1"
-
     PKG_PATH="$EPM_PKG_PATH/$UNINSTALL_PACKAGE"
-    PKG_BIN_PATH="$BIN_PATH/$UNINSTALL_PACKAGE"
-    PKG_ENV_PATH=""
-    if file_exists $PKG_PATH/$ENV_NIX/$PKG_UNINSTALL_FILE_NAME; then
-        log_debug "Uninstall script found for nix environment"
-        PKG_ENV_PATH=$PKG_PATH/$ENV_NIX
-    elif file_exists $PKG_PATH/$ENV_ALL/$PKG_UNINSTALL_FILE_NAME; then
-        log_debug "Uninstall script found for all environment"
-        PKG_ENV_PATH=$PKG_PATH/$ENV_ALL
-    else
-        command_fail "Uninstall script was not found in $PKG_PATH"
-    fi
 
-    PKG_TYPE="$(pkg_config_get_type "$UNINSTALL_PACKAGE")"
+    PKG_ENV="$(pkg_env "$UNINSTALL_PACKAGE")"
+    PKG_ENV_PATH="$PKG_PATH/$PKG_ENV"
     PKG_UNINSTALL_SH_PATH="$PKG_ENV_PATH/$PKG_UNINSTALL_FILE_NAME"
 
     log_debug "Loading $PROGRAM_NAME configuration located at \"$EPM_ENV_FILE_PATH\""
     source "$EPM_ENV_FILE_PATH"
+    log_debug "Loading $PROGRAM_NAME libraries located at \"$EPM_LIB_FILE_PATH\""
     source "$EPM_LIB_FILE_PATH"
 
-    case "$PKG_TYPE" in
-        "$PKG_TYPE_SINGLE")
-            log_debug "Executing single uninstall script"
-            if $PKG_UNINSTALL_SH_PATH; then
-                data_config_remove "$UNINSTALL_PACKAGE"
-            else
-                command_fail
-            fi
-            ;;
-        "$PKG_TYPE_BUNDLE")
-            log_debug "Executing bundle uninstall script"
-            $PKG_UNINSTALL_SH_PATH
-            ;;
-        *)
-            command_fail "Invalid package type $INSTALL_PACKAGE_TYPE"
-            ;;
-    esac
+    if $PKG_UNINSTALL_SH_PATH; then
+        data_config_remove "$UNINSTALL_PACKAGE"
+    else
+        command_fail
+    fi
 }
 
 get_uninstall_dependencies() {
@@ -1506,7 +1585,7 @@ get_uninstall_dependencies() {
         PKG_CURRENT="${PKG_IN_LIST[0]}"
         if data_has_package "$PKG_CURRENT"; then
             PKG_OUT_LIST["$PKG_CURRENT"]=$PKG_LEVEL
-
+            
             while read -r PKG; do
                 if ! empty "$PKG" && data_has_package "$PKG"; then
                     PKG_IN_LIST+=("$PKG")
@@ -1517,7 +1596,7 @@ get_uninstall_dependencies() {
         (( PKG_LEVEL++ ))
         PKG_IN_LIST=("${PKG_IN_LIST[@]:1}")
     done
-
+    
     for KEY in "${!PKG_OUT_LIST[@]}"; do
         echo ${PKG_OUT_LIST["$KEY"]} "$KEY"
     done | sort -rn -k1 | cut -f2 -d' '
@@ -1557,7 +1636,17 @@ uninstall_package_exec() {
 
 uninstall_package() {
     while read -r PKG; do
-        uninstall_package_exec "$PKG"
+        local PKG_TYPE="$(pkg_config_get_type "$PKG")"
+        
+        if [ "$PKG" == "$1" ]; then
+            uninstall_package_exec "$PKG"
+        else
+            if data_config_is_single "$PKG"; then
+                uninstall_package_exec "$PKG"
+            elif data_config_is_bundle "$PKG"; then
+                data_config_remove "$PKG" 
+            fi
+        fi
     done <<< "$(get_uninstall_dependencies "$1")"
 }
 
@@ -1629,50 +1718,32 @@ install_exec() {
     PKG_PATH="$EPM_PKG_PATH/$INSTALL_PACKAGE"
 
     pull_exec "$INSTALL_PACKAGE"
-    if dir_exists "$PKG_PATH/$ENV_NIX"; then
-        log_debug "Proceding with nix package"
-        PKG_ENV="$ENV_NIX"
-        PKG_ENV_PATH="$PKG_PATH/$PKG_ENV"
-    elif dir_exists "$PKG_PATH/$ENV_ALL"; then
-        log_debug "Proceding with all package"
-        PKG_ENV=$ENV_ALL
-        PKG_ENV_PATH=$PKG_PATH/$PKG_ENV
-    else 
-        command_fail "Invalid package folder $INSTALL_PACKAGE"
-    fi
+    PKG_ENV="$(pkg_env "$INSTALL_PACKAGE")"
+    PKG_ENV_PATH="$PKG_PATH/$PKG_ENV"
     PKG_TYPE="$(pkg_config_get_type "$INSTALL_PACKAGE")"
     PKG_PARENT="$(pkg_config_get_parent "$INSTALL_PACKAGE")"
     PKG_DEPENDENCIES="$(pkg_config_get_dependencies "$INSTALL_PACKAGE")"
+    PKG_DESCRIPTION="$(pkg_config_get_description "$INSTALL_PACKAGE")"
     PKG_INSTALL_SH_PATH="$PKG_ENV_PATH/$PKG_INSTALL_FILE_NAME"
 
     log_debug "Loading $PROGRAM_NAME configuration located at \"$EPM_ENV_FILE_PATH\""
     source "$EPM_ENV_FILE_PATH" 
+    log_debug "Loading $PROGRAM_NAME libraries located at \"$EPM_LIB_FILE_PATH\""
     source "$EPM_LIB_FILE_PATH"
 
-    INSTALL_PACKAGE_TYPE="${PACKAGE_TYPE:-"$PKG_TYPE_SINGLE"}"
-    case "$PKG_TYPE" in
-        "$PKG_TYPE_SINGLE")
-            log_debug "Executing single install script"
-
-            if $PKG_INSTALL_SH_PATH; then
-                data_config_add "$INSTALL_PACKAGE"\
-                    "$PKG_TYPE_SINGLE"\
-                    "$PKG_ENV"\
-                    "$PKG_PARENT"\
-                    "$PKG_DEPENDENCIES"\
-                    "$PKG_DESCRIPTION"
-            else
-                command_fail
-            fi
-            ;;
-        "$PKG_TYPE_BUNDLE")
-            log_debug "Executing bundle install script"
-
-            $PKG_INSTALL_SH_PATH
-            ;;
-        *)
-            command_fail "Invalid package type $INSTALL_PACKAGE_TYPE"
-    esac
+    data_config_add "$INSTALL_PACKAGE"\
+        "$PKG_TYPE"\
+        "$PKG_ENV"\
+        "$PKG_PARENT"\
+        "$PKG_DEPENDENCIES"\
+        "$PKG_DESCRIPTION"
+    
+    log_debug "Executing \"$PKG_TYPE\" install script"
+    if ! $PKG_INSTALL_SH_PATH; then
+        log_debug "Installation of package \"$INSTALL_PACKAGE\" failed"
+        data_config_remove "$INSTALL_PACKAGE"             
+        command_fail
+    fi
 }
 
 get_install_dependencies() {
@@ -1722,7 +1793,7 @@ install_check() {
     fi
 
     if data_has_package "$1"; then
-        yesNo "$1 already installed, reinstall? "
+        command_usage "$USAGE_CMD" "$USAGE_CMD_SYNOPSIS" "$USAGE_CMD_DESCRIPTION" "Package \"$1\" is already installed"
     fi
 }
 
@@ -1749,12 +1820,7 @@ install() {
 
     install_check "$1"
 
-    if data_has_package "$1"; then
-        log_debug "Package \"$1\" is already installed, updating it"
-    else
-        log_debug "Package \"$1\" is not installed proceding with the installation"
-        install_package "$1"
-    fi
+    install_package "$1"
 }
 
 require_check() {
@@ -1771,16 +1837,35 @@ require_check() {
     elif ! is_package "$1"; then
         command_usage "$USAGE_CMD" "$USAGE_CMD_SYNOPSIS" "$USAGE_CMD_DESCRIPTION" "Invalid package name: \"$1\""
     fi
+
+    if ! empty "$2" && ! is_package "$2"; then
+        command_usage "$USAGE_CMD" "$USAGE_CMD_SYNOPSIS" "$USAGE_CMD_DESCRIPTION" "Invalid package name: \"$2\""
+    fi
 }
 
 require() {
-    log_debug "Executing the require command with \"$1\""
+    log_debug "Executing the require command with \"$1\" and \"$2\""
 
-    require_check "$1"
+    require_check "$1" "$2"
 
     if ! data_has_package "$1"; then
         log_debug "Package \"$1\" is not installed proceding with the installation"
         install_package "$1"
+        if ! empty "$2"; then
+            log_debug "Adding dependency \"$1\" to \"$2\""
+            data_config_add_dependencies "$2" "$1"            
+        fi
+    else
+        log_debug "Package \"$1\" is installed checking dependent"
+        if ! empty "$2"; then
+            local PKG_DEPENDENCIES="$(pkg_config_get_dependencies "$2")"
+            if [[ $PKG_DEPENDENCIES == *$1*  ]]; then
+                log_debug "Dependency \"$1\" is on package "\"$2\"" dependencies"
+            else
+                log_debug "Dependency \"$1\" is not package "\"$2\"" dependencies, adding it"
+                data_config_add_dependencies "$2" "$1"            
+            fi
+        fi
     fi
 }
 
@@ -1874,7 +1959,7 @@ pack() {
 }
 
 push_exec() {
-    PUSH_PACKAGE=$1
+    PUSH_PACKAGE="$1"
     PUSH_ENV="$(pkg_env "$PUSH_PACKAGE")"
     PKG_PATH="$EPM_PKG_PATH/$PUSH_PACKAGE"
     EPM_PKG_SRV="$(env_get "$EPM_PKG_SRV_KEY")"
@@ -2471,7 +2556,7 @@ case "$CMD" in
         install "$2"
         ;;
     -r|require)
-        require "$2"
+        require "$2" "$3"
         ;;
     -u|uninstall)
         uninstall "$2"
